//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 12:27:50 AM EDT 
//


package matrix.assemblyconfig.generic.config.model;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://matrix.pubmatic.com/matrix/reports}assemblyFields"/>
 *         &lt;element ref="{http://matrix.pubmatic.com/matrix/reports}joins"/>
 *         &lt;element ref="{http://matrix.pubmatic.com/matrix/reports}filter" minOccurs="0"/>
 *         &lt;element name="output-sink-mode" type="{http://matrix.pubmatic.com/matrix/reports}output-sink-mode"/>
 *         &lt;element ref="{http://matrix.pubmatic.com/matrix/reports}outputSequence"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="applicable-date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assemblyFields",
    "joins",
    "outputSinkMode",
    "assemblyGroups",
    "meta"
})
@XmlRootElement(name = "assembly")
public class Assembly implements Serializable{

    @XmlElement(required = true)
    protected AssemblyFields assemblyFields;
    @XmlElement(required = true)
    protected Joins joins;
    @XmlElement(name = "output-sink-mode", required = true)
    protected OutputSinkMode outputSinkMode;
    @XmlElement(required = true)
    protected AssemblyGroups assemblyGroups;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "applicable-date")
    protected String applicableDate;
    @XmlElement(required = true)
    protected Meta meta;

    /**
     * Gets the value of the assemblyFields property.
     * 
     * @return
     *     possible object is
     *     {@link AssemblyFields }
     *     
     */
    public AssemblyFields getAssemblyFields() {
        return assemblyFields;
    }

    /**
     * Sets the value of the assemblyFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssemblyFields }
     *     
     */
    public void setAssemblyFields(AssemblyFields value) {
        this.assemblyFields = value;
    }

    /**
     * Gets the value of the joins property.
     * 
     * @return
     *     possible object is
     *     {@link Joins }
     *     
     */
    public Joins getJoins() {
        return joins;
    }

    /**
     * Sets the value of the joins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Joins }
     *     
     */
    public void setJoins(Joins value) {
        this.joins = value;
    }

    /**
     * Gets the value of the outputSinkMode property.
     * 
     * @return
     *     possible object is
     *     {@link OutputSinkMode }
     *     
     */
    public OutputSinkMode getOutputSinkMode() {
        return outputSinkMode;
    }

    /**
     * Sets the value of the outputSinkMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputSinkMode }
     *     
     */
    public void setOutputSinkMode(OutputSinkMode value) {
        this.outputSinkMode = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the applicableDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicableDate() {
        return applicableDate;
    }

    /**
     * Sets the value of the applicableDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicableDate(String value) {
        this.applicableDate = value;
    }

    public AssemblyGroups getAssemblyGroups() {
      return assemblyGroups;
    }

    public void setAssemblyGroups(AssemblyGroups assemblyGroups) {
      this.assemblyGroups = assemblyGroups;
    }
    
    public Meta getMeta() {
      return meta;
    }

    public void setMeta(Meta meta) {
      this.meta = meta;
    }

    public Map<String, Map<Integer, FieldType>> getGroupWiseCubicFieldPositionAndTypeMap(String[] fieldPostions) {
      
      Map<String, Map<Integer, FieldType>> groupWiseCubicFieldPositionAndTypeMap = new HashMap<>();
      Map<String, List<String>> groupWiseCubicFieldMap = getAssemblyGroups().getGroupAndCubicFieldMap();
      Map<String, FieldType> fieldAndTypeMap = assemblyFields.getDimensions().getFieldAndTypeMap();
      for(String group : groupWiseCubicFieldMap.keySet()){
        Map<String, FieldType> cubicFieldAndTypeMap = new HashMap<>();
        List<String> cubicFields = groupWiseCubicFieldMap.get(group);
        for(String field : cubicFields){
          cubicFieldAndTypeMap.put(field, fieldAndTypeMap.get(field));
        }
        groupWiseCubicFieldPositionAndTypeMap.put(group, getFieldPositionAndTypeMap(fieldPostions, cubicFieldAndTypeMap));
      }
      return groupWiseCubicFieldPositionAndTypeMap;
    }
    

    /*public boolean hasGroupsWithCubicFields(){
      return !getGroupWiseCubicFieldPositionAndTypeMap().isEmpty();
    }*/

    private Map<Integer, FieldType> getFieldPositionAndTypeMap(String[] fields, Map<String, FieldType> fieldAndTypeMap){
      Map<Integer, FieldType> fieldPositionAndTypeMap = new HashMap<>();
      for(int i=0;i<fields.length;i++){
        String field = fields[i];
        if(fieldAndTypeMap.containsKey(field)){
          fieldPositionAndTypeMap.put(i, fieldAndTypeMap.get(field));
        }
      }
      return fieldPositionAndTypeMap;
    }
}
