//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.25 at 08:58:02 AM EDT 
//


package matrix.assemblyconfig.generic.config.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://matrix.pubmatic.com/matrix/reports}assemblyGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assemblyGroup"
})
@XmlRootElement(name = "assemblyGroups")
public class AssemblyGroups implements Serializable{

    @XmlElement(required = true)
    protected List<AssemblyGroup> assemblyGroup;

    /**
     * Gets the value of the assemblyGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assemblyGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssemblyGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssemblyGroup }
     * 
     * 
     */
    public List<AssemblyGroup> getAssemblyGroup() {
        if (assemblyGroup == null) {
            assemblyGroup = new ArrayList<AssemblyGroup>();
        }
        return this.assemblyGroup;
    }
    
    public AssemblyGroup getAssemblyGroup(AssemblyGroupName groupName){
      AssemblyGroup group = null;
      for(AssemblyGroup g : assemblyGroup){
        if(g.getName().equals(groupName)){
          group = g;
          break;
        }
      }
      return group;
    }
    
    public Map<String, List<String>> getGroupAndCubicFieldMap(){
      Map<String, List<String>> groupAndCubicFieldMap = new HashMap<String, List<String>>();
      for(AssemblyGroup group : assemblyGroup){
        List<String> cubicFields = group.getCubicFields();
        if(!cubicFields.isEmpty()){
          groupAndCubicFieldMap.put(group.getName().toString(), group.getCubicFields());
        }
      }
      return groupAndCubicFieldMap;
    }

}
