//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.25 at 08:06:26 AM EDT 
//


package matrix.assemblyconfig.generic.config.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://matrix.pubmatic.com/matrix/reports}assemblyGroupDimension" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assemblyGroupDimension"
})
@XmlRootElement(name = "assemblyGroupDimensions")
public class AssemblyGroupDimensions implements Serializable{

    @XmlElement(required = true)
    protected List<AssemblyGroupDimension> assemblyGroupDimension;

    /**
     * Gets the value of the assemblyGroupDimension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assemblyGroupDimension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssemblyGroupDimension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssemblyGroupDimension }
     * 
     * 
     */
    public List<AssemblyGroupDimension> getAssemblyGroupDimension() {
        if (assemblyGroupDimension == null) {
            assemblyGroupDimension = new ArrayList<AssemblyGroupDimension>();
        }
        return this.assemblyGroupDimension;
    }
    
    public String[] getAssemblyGroupDimensionArray()
    {
      if(assemblyGroupDimension==null || assemblyGroupDimension.size()==0)
      {
        return null;
      }else
      {
        String[] assemblyGroupDimensionArray=new String[assemblyGroupDimension.size()];
        int i=0;
        for(AssemblyGroupDimension dimension: assemblyGroupDimension)
        {
          assemblyGroupDimensionArray[i++]=dimension.getName();
        }
        
        return assemblyGroupDimensionArray;
      }
    }
}
