//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 12:27:50 AM EDT 
//


package matrix.assemblyconfig.generic.config.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://matrix.pubmatic.com/matrix/reports}derivedFromOtherMetric" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "derivedFromOtherMetric"
})
@XmlRootElement(name = "derivedFromOtherMetrics")
public class DerivedFromOtherMetrics implements Serializable{

    @XmlElement(required = true)
    protected List<DerivedFromOtherMetric> derivedFromOtherMetric;

    /**
     * Gets the value of the derivedFromOtherMetric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the derivedFromOtherMetric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDerivedFromOtherMetric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DerivedFromOtherMetric }
     * 
     * 
     */
    public List<DerivedFromOtherMetric> getDerivedFromOtherMetric() {
        if (derivedFromOtherMetric == null) {
            derivedFromOtherMetric = new ArrayList<DerivedFromOtherMetric>();
        }
        return this.derivedFromOtherMetric;
    }

    public String[] getDerivedMetricNames(){
      String[] derivedMetricNames = new String[derivedFromOtherMetric.size()];
      int i=0;
      for(DerivedFromOtherMetric derivedMetrics : derivedFromOtherMetric){
        derivedMetricNames[i] = derivedMetrics.getName();
        i++;
      }
      return derivedMetricNames;
    }
    
    public Map<String, FieldType> getFieldAndTypeMap(){
      Map<String, FieldType> fieldAndTypeMap = new HashMap<String, FieldType>();
      for(DerivedFromOtherMetric metric : derivedFromOtherMetric){
        fieldAndTypeMap.put(metric.getName(), metric.getType());
      }
      return fieldAndTypeMap;
    }
}
