//
  // This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 12:04:09 AM EDT 
//


package matrix.assemblyconfig.generic.config.model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://matrix.pubmatic.com/matrix/reports}fromDimensions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "type",
    "className",
    "fromDimensions"
})
@XmlRootElement(name = "derivedFromOtherDimension")
public class DerivedFromOtherDimension implements Serializable{

    @XmlElement(required = true)
    protected String name;
    protected FieldType type = FieldType.INTEGER;
    @XmlElement(required = true)
    protected String className;
    @XmlElement(required = true)
    protected FromDimensions fromDimensions;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the fromDimensions property.
     * 
     * @return
     *     possible object is
     *     {@link FromDimensions }
     *     
     */
    public FromDimensions getFromDimensions() {
        return fromDimensions;
    }

    /**
     * Sets the value of the fromDimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link FromDimensions }
     *     
     */
    public void setFromDimensions(FromDimensions value) {
        this.fromDimensions = value;
    }
    
       
    public FieldType getType() {
      return type;
    }

    public void setType(FieldType type) {
      this.type = type;
    }

}
