//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.25 at 08:58:02 AM EDT 
//


package matrix.assemblyconfig.generic.config.model;

import java.io.Serializable;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dimensionSequences"
})
@XmlRootElement(name = "extractorDimensionSequences")
public class ExtractorDimensionSequences implements Serializable{

    @XmlElement(required = true)
    protected List<DimensionSequences> dimensionSequences;

    public List<DimensionSequences> getDimensionSequences() {
      return dimensionSequences;
    }

    public void setDimensionSequences(List<DimensionSequences> dimensionSequences) {
      this.dimensionSequences = dimensionSequences;
    }
    
 }
