//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 12:27:50 AM EDT 
//


package matrix.assemblyconfig.generic.config.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fieldType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fieldType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LONG"/>
 *     &lt;enumeration value="INTEGER"/>
 *     &lt;enumeration value="DOUBLE"/>
 *     &lt;enumeration value="STRING"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "fieldType")
@XmlEnum
public enum FieldType {

    LONG,
    INTEGER,
    DOUBLE,
    STRING;

    public String value() {
        return name();
    }

    public static FieldType fromValue(String v) {
        return valueOf(v);
    }
    
    public static Class getFieldTypeClass(FieldType type) {
      switch (type) {
        case DOUBLE:
          return Double.class;
        case INTEGER:
          return Integer.class;
        case LONG:
          return Long.class;
        case STRING:
          return String.class;
        default:
          throw new RuntimeException("Invalid Field Type [ " + type + " ]");
      }
    }

}
