//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 12:27:50 AM EDT 
//


package matrix.assemblyconfig.generic.config.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the matrix.datacrunching.generic.config.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: matrix.datacrunching.generic.config.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Assemblies }
     * 
     */
    public Assemblies createAssemblies() {
        return new Assemblies();
    }

    /**
     * Create an instance of {@link Assembly }
     * 
     */
    public Assembly createAssembly() {
        return new Assembly();
    }

    /**
     * Create an instance of {@link AssemblyFields }
     * 
     */
    public AssemblyFields createAssemblyFields() {
        return new AssemblyFields();
    }

    /**
     * Create an instance of {@link Dimensions }
     * 
     */
    public Dimensions createDimensions() {
        return new Dimensions();
    }

    /**
     * Create an instance of {@link SimpleDimensions }
     * 
     */
    public SimpleDimensions createSimpleDimensions() {
        return new SimpleDimensions();
    }

    /**
     * Create an instance of {@link SimpleDimension }
     * 
     */
    public SimpleDimension createSimpleDimension() {
        return new SimpleDimension();
    }

    /**
     * Create an instance of {@link DerivedFromJoinDimensions }
     * 
     */
    public DerivedFromJoinDimensions createDerviedFromJoinDimensions() {
        return new DerivedFromJoinDimensions();
    }

    /**
     * Create an instance of {@link DerivedFromJoinDimension }
     * 
     */
    public DerivedFromJoinDimension createDerviedFromJoinDimension() {
        return new DerivedFromJoinDimension();
    }

    /**
     * Create an instance of {@link Metrics }
     * 
     */
    public Metrics createMetrics() {
        return new Metrics();
    }

    /**
     * Create an instance of {@link SimpleMetrics }
     * 
     */
    public SimpleMetrics createSimpleMetrics() {
        return new SimpleMetrics();
    }

    /**
     * Create an instance of {@link SimpleMetric }
     * 
     */
    public SimpleMetric createSimpleMetric() {
        return new SimpleMetric();
    }

    /**
     * Create an instance of {@link DerivedFromOtherMetrics }
     * 
     */
    public DerivedFromOtherMetrics createDerivedFromOtherMetrics() {
        return new DerivedFromOtherMetrics();
    }

    /**
     * Create an instance of {@link DerivedFromOtherMetric }
     * 
     */
    public DerivedFromOtherMetric createDerivedFromOtherMetric() {
        return new DerivedFromOtherMetric();
    }

    /**
     * Create an instance of {@link FromMetrics }
     * 
     */
    public FromMetrics createFromMetrics() {
        return new FromMetrics();
    }

    /**
     * Create an instance of {@link Joins }
     * 
     */
    public Joins createJoins() {
        return new Joins();
    }

    /**
     * Create an instance of {@link Join }
     * 
     */
    public Join createJoin() {
        return new Join();
    }

    /**
     * Create an instance of {@link JoinFields }
     * 
     */
    public JoinFields createJoinFields() {
        return new JoinFields();
    }

    /**
     * Create an instance of {@link JoinField }
     * 
     */
    public JoinField createJoinField() {
        return new JoinField();
    }

    /**
     * Create an instance of {@link WithDimensions }
     * 
     */
    public WithDimensions createWithDimensions() {
        return new WithDimensions();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }


}
