//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 12:27:50 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://matrix.pubmatic.com/matrix/reports", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package matrix.assemblyconfig.generic.config.model;
