//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 12:27:50 AM EDT 
//


package matrix.assemblyconfig.generic.config.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import matrix.assemblyconfig.generic.config.util.AggregateByUtil;
import cascading.pipe.assembly.AggregateBy;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://matrix.pubmatic.com/matrix/reports}simpleMetric" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "simpleMetric"
})
@XmlRootElement(name = "simpleMetrics")
public class SimpleMetrics implements Serializable{

    @XmlElement(required = true)
    protected List<SimpleMetric> simpleMetric;

    /**
     * Gets the value of the simpleMetric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simpleMetric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimpleMetric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleMetric }
     * 
     * 
     */
    public List<SimpleMetric> getSimpleMetric() {
        if (simpleMetric == null) {
            simpleMetric = new ArrayList<SimpleMetric>();
        }
        return this.simpleMetric;
    }
    
    public String[] getMetricNames(){
      String[] metricNames = new String[simpleMetric.size()];
      int i=0;
      for (SimpleMetric metric : simpleMetric) {
        metricNames[i] = metric.getName();
        i++;
      }
      return metricNames;
    }
    
    /**
     * Gets AggregateBy Sub assemblies based on aggregation type defined in xml
     * @return
     */
    public AggregateBy[] getAggregateBySubAssemblies(){
      AggregateBy[] aggregateBy = new AggregateBy[simpleMetric.size()];
      int i=0;
      for(SimpleMetric m : simpleMetric){
        m.getType();
        aggregateBy[i] = AggregateByUtil.createAggregateByFromMetric(m.getOperation(), m.getName(), m.getType());
        i++;
      }
      return aggregateBy;
    }

    public Map<String, FieldType> getFieldAndTypeMap(){
      Map<String, FieldType> fieldAndTypeMap = new HashMap<String, FieldType>();
      for(SimpleMetric metric : simpleMetric){
        fieldAndTypeMap.put(metric.getName(), metric.getType());
      }
      return fieldAndTypeMap;
    }

}
