//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 12:27:50 AM EDT 
//


package matrix.assemblyconfig.generic.config.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang3.ArrayUtils;




/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://matrix.pubmatic.com/matrix/reports}simpleDimension" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "simpleDimension"
})
@XmlRootElement(name = "simpleDimensions")
public class SimpleDimensions implements Serializable{

    @XmlElement(required = true)
    protected List<SimpleDimension> simpleDimension;
    
    @XmlTransient
    private Map<String, SimpleDimension> simpleDimensionMap;

    /**
     * Gets the value of the simpleDimension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simpleDimension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimpleDimension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleDimension }
     * 
     * 
     */
    public List<SimpleDimension> getSimpleDimension() {
        if (simpleDimension == null) {
            simpleDimension = new ArrayList<SimpleDimension>();
        }
        return this.simpleDimension;
    }
    
    /**
     * Gets name of dimensions in the order defined in xml
     * @return
     */
    public String[] getDimensionNames(){
      String[] dimensionNames = new String[simpleDimension.size()];
      int i=0;
      for(SimpleDimension d : simpleDimension){
        dimensionNames[i]=d.getName();
        i++;
      }
      return dimensionNames;
    }
    
    public String[] getDimensionsNamesWithGroupKey(){
      return ArrayUtils.addAll(new String[]{"group_key"}, getDimensionNames());
    }
    
    public SimpleDimension getSimpleDimension(String name){
      if(simpleDimensionMap == null){
        initializeSimpleDimensionMap();
      }
      return simpleDimensionMap.get(name);
    }

    private void initializeSimpleDimensionMap() {
      simpleDimensionMap = new HashMap<>();
      for(SimpleDimension dimension : simpleDimension){
        simpleDimensionMap.put(dimension.getName(), dimension);
      }
    }
    
    /*public List<String> getCubicFields(){
      List<String> cubicFields = new ArrayList<>();
      for(int i=0; i<simpleDimension.size() ;i++){
        SimpleDimension dimension = simpleDimension.get(i);
        if(dimension.isIsCubic()){
          cubicFields.add(dimension.getName());
        }
      }
      return cubicFields;
    }*/
    
    /*public Map<String, FieldType> getCubicFieldAndTypeMap(){
      return getFieldAndTypeMap(true);
    }*/
    
    public Map<String, FieldType> getFieldAndTypeMap(){
      Map<String, FieldType> fieldAndTypeMap = new HashMap<>();
      for(int i=0; i<simpleDimension.size() ;i++){
        SimpleDimension dimension = simpleDimension.get(i);
        fieldAndTypeMap.put(dimension.getName(), dimension.getType());
      }
      return fieldAndTypeMap;
    }

}
